### ISSUE TITLE
Web development – choice of frameworks

### ISSUE THREAD

**Issue by airstrike** [github/archive-program#71]
I'll be the first to admit I'm biased, but is there a reason why the list would favor Flask over Django, particularly when the latter is arguably more popular, robust and mature?

I see Ruby on Rails is favored over Sinatra, so size / scope doesn't seem to be the deciding factor.

**Comment by rezendi** [comment]
Thanks for this; will consider. (I'm more a Django than Flask dev myself, actually.) We're open to PRs nominating new material --

**Comment by nferraz** [comment]
I'm trying to consolidate several ideas in the ticket #88 (Guidelines).

One of my recommendations is that we should focus on general principles instead of specific implementations.

Otherwise we will open a can of worms, where each topic will lead to tens or hundreds of implementations (Flask, Django, Rails, Sinatra, and a myriad of web frameworks).

So, what are the general principles behind web development?

- HTML (do you believe we forgot it??? That's a sign that we are forgetting the trunk and focusing on the leafs)
- HTTP
- REST

And so on.

**Comment by rezendi** [comment]
Django book added --
